export default function TermsOfServicePage() {
  return (
    <div className="legal-page">
      <header className="app-header">
        <h1>Terms of Service</h1>
        <p className="app-subtitle">Last updated: 2026-09-29</p>
      </header>

      <h2>1. What this Service is</h2>
      <p>
        9Band (the "Service") is an AI-assisted practice tool for the IELTS exam format. It
        provides practice essays, speaking, reading, and listening exercises, and AI-generated
        feedback and estimated band scores.
      </p>
      <p>
        <strong>
          The Service is not affiliated with, endorsed by, or connected to IELTS, the British
          Council, IDP: IELTS Australia, or Cambridge Assessment English.
        </strong>{' '}
        "IELTS" is used here only to describe the exam format this Service helps you practice
        for.
      </p>
      <p>
        <strong>Scores are estimates, not certified results.</strong> All band scores and
        feedback are generated by AI models and are intended as a diagnostic study aid. They are
        not official IELTS scores, are not issued or endorsed by any IELTS test provider, and are
        not a guarantee of your actual exam result.
      </p>

      <h2>2. Accounts</h2>
      <p>
        You need an account to use most of the Service. You agree to provide accurate
        information when creating one, and to keep your login credentials to yourself — you're
        responsible for activity on your account.
      </p>
      <p>
        <strong>Age and school use.</strong> If you are under the age of 18, you may only use the
        Service with the involvement of a parent, guardian, or a school that has agreed to these
        terms on your behalf, as described in our Privacy Policy.
      </p>
      <p>
        <strong>Teacher and admin accounts.</strong> Teachers are given account access by 9Band
        or by their school administrator, not through self-signup. A teacher may view and comment
        on the practice content and scores of students enrolled in their own class, as described
        in our Privacy Policy.
      </p>

      <h2>3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Submit content that is unlawful, abusive, or that you don't have the right to submit.</li>
        <li>Attempt to circumvent rate limits, usage caps, or other technical restrictions on the Service.</li>
        <li>Use the Service to generate content unrelated to IELTS practice, or attempt to manipulate the AI grading system to produce false or misleading scores.</li>
        <li>Share your account credentials with others, or use another user's account.</li>
        <li>Attempt to access another student's practice content, recordings, or scores outside of the class-visibility features built into the Service.</li>
      </ul>
      <p>We may suspend or terminate accounts that violate these terms.</p>

      <h2>4. Your content</h2>
      <p>
        You retain ownership of the essays, recordings, and other content you submit ("Your
        Content"). By submitting Your Content, you grant us a license to process it — including
        sending it to the third-party AI providers described in our Privacy Policy — solely for
        the purpose of providing the Service to you (generating feedback and scores, storing your
        history, and showing it to your teacher if you're enrolled in a class).
      </p>
      <p>
        We do not claim ownership of Your Content, and we do not use it to train AI models
        ourselves. Our AI providers' own policies on this vary: Anthropic (Claude) and Groq do not
        use API-submitted content to train their models, on any tier. Google's Gemini API does
        not train on paid-tier traffic, but <strong>does</strong> permit itself to use free-tier
        traffic (including human review) to improve its models — the Service is currently on
        Gemini's free tier while a move to paid tier is in progress, and this section will be
        updated the moment that switch completes.
      </p>

      <h2>5. Payment and subscriptions</h2>
      <p>
        All features are currently free while the Service is in this phase — no charges apply.
        Pricing, billing cycle, and cancellation terms will be added here once paid plans are
        reintroduced, processed through Stripe.
      </p>

      <h2>6. Disclaimers and limitation of liability</h2>
      <p>
        The Service is provided "as is." AI-generated feedback and scores may contain errors, and
        we make no guarantee that they match the score you would receive on a real IELTS exam. To
        the fullest extent permitted by law, 9Band is not liable for exam outcomes, decisions made
        based on Service feedback, or indirect or consequential damages arising from use of the
        Service.
      </p>

      <h2>7. School and teacher partnerships</h2>
      <p>
        Where the Service is used through a partner school, the school is responsible for:
        obtaining any required parental/guardian consent for students under the applicable age,
        designating which staff receive teacher accounts, and being the point of contact for its
        own students' questions about their data.
      </p>

      <h2>8. Changes to the Service and these terms</h2>
      <p>
        We may update these terms or change the Service over time. If we make material changes to
        these terms, we'll update the "Last updated" date and, where required, notify you or your
        school directly.
      </p>

      <h2>9. Termination</h2>
      <p>
        You may stop using the Service and request account deletion at any time (see our Privacy
        Policy for how). We may suspend or terminate your access for violating these terms.
      </p>

      <h2>10. Governing law</h2>
      <p>This section is still being finalized and will be added once settled.</p>

      <h2>11. Contact</h2>
      <p>
        Questions about these terms can be sent to{' '}
        <a href="mailto:okibzyabang@gmail.com">okibzyabang@gmail.com</a>.
      </p>
    </div>
  );
}
